### PR TITLE
Fixes regression in resource list component

### PR DESCRIPTION
**Pull request by cspanring**
* fixes a regression introduced in #14 
* adds proper start and stop behavior for Pretender (#14 was `only` running one test...)

@davidbilling thanks for merging! and sorry for the trouble, should've caught this in #14.

### CODE REVIEW

**Comment by cspanring** [comment]
@davidbilling additional changes to make ember-try pass on travis:

* remove bower dependency
* switch ember-try to yarn as workaround for https://github.com/ember-cli/ember-try/issues/207
* remove older LTS from ember-try (keeping most recent LTS as good practice)

**Comment by davidbilling** [comment]
@cspanring Thanks, I did a update with Ember-cli-update to 3.4, but that was revoced and something when sideways when reverting it. I have not had any time looking into it. 
Really appreciate that you trying to fix the ember:try test!

**Comment by cspanring** [comment]
all tests in ember-try are now passing, except LTS 2.16, which is not in the ember-try config and I'm not sure why travis is trying to run it.

**Comment by davidbilling** [comment]
@cspanring It is in travis.yml I think...
env: EMBER_TRY_SCENARIO=ember-lts-2.16

**Comment by cspanring** [comment]
trying a few combinations to make travis happy, will squash the commits once I found the correct combo...

**Comment by davidbilling** [comment]
🥇 Thanks!

**Comment by cspanring** [comment]
@davidbilling all set, ember-try and travis are now happy

**Pull request merged**
